[tox]
envlist = py311, py312, py313, build
isolated_build = true

[testenv]
allowlist_externals = uv
commands =
    uv sync --active --locked --all-extras --dev
    ruff check .
    ruff format --check .
    pytest -q

[testenv:build]
allowlist_externals = uv
commands = uv build
